"""Add StepConnection model and relationships

Revision ID: 2292096d8c80
Revises: 9dd481ea00e0
Create Date: 2025-05-09 23:27:31.329692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2292096d8c80'
down_revision = '9dd481ea00e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_step_id', sa.Integer(), nullable=False),
    sa.Column('target_step_id', sa.Integer(), nullable=False),
    sa.Column('journey_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ),
    sa.ForeignKeyConstraint(['source_step_id'], ['steps.id'], ),
    sa.ForeignKeyConstraint(['target_step_id'], ['steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('step_connections')
    # ### end Alembic commands ###
