"""Rename models and tables to English (User, Journey, Step, Cost)2

Revision ID: 9dd481ea00e0
Revises: f490d58208e3
Create Date: 2025-05-06 00:28:29.124179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dd481ea00e0'
down_revision = 'f490d58208e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('creat_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('journeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modificated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journeys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journeys_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_journeys_user_id'), ['user_id'], unique=False)

    op.create_table('steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=True),
    sa.Column('budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('date_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('pos_x', sa.Integer(), nullable=True),
    sa.Column('pos_y', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modificated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('journey_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_steps_journey_id'), ['journey_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_steps_type'), ['type'], unique=False)

    op.create_table('costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_type', sa.String(length=50), nullable=False),
    sa.Column('occoured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timePeriod_start', sa.Date(), nullable=True),
    sa.Column('timePeriod_end', sa.Date(), nullable=True),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modificated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('costs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_costs_cost_type'), ['cost_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_costs_occoured_at'), ['occoured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_costs_step_id'), ['step_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('costs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_costs_step_id'))
        batch_op.drop_index(batch_op.f('ix_costs_occoured_at'))
        batch_op.drop_index(batch_op.f('ix_costs_cost_type'))

    op.drop_table('costs')
    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_steps_type'))
        batch_op.drop_index(batch_op.f('ix_steps_journey_id'))

    op.drop_table('steps')
    with op.batch_alter_table('journeys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journeys_user_id'))
        batch_op.drop_index(batch_op.f('ix_journeys_name'))

    op.drop_table('journeys')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
