"""Create initial database schema with Usuario, Jornada, Passo, Custo tables

Revision ID: f490d58208e3
Revises: 
Create Date: 2025-05-05 19:08:04.704521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f490d58208e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('jornadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('data_modificacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jornadas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jornadas_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_jornadas_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('passos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('canal', sa.String(length=100), nullable=True),
    sa.Column('orcamento', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('data_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_fim', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('pos_x', sa.Integer(), nullable=True),
    sa.Column('pos_y', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('data_modificacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('jornada_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('passos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_passos_jornada_id'), ['jornada_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_passos_tipo'), ['tipo'], unique=False)

    op.create_table('custos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tipo_custo', sa.String(length=50), nullable=False),
    sa.Column('data_ocorrencia', sa.DateTime(timezone=True), nullable=False),
    sa.Column('periodo_inicio', sa.Date(), nullable=True),
    sa.Column('periodo_fim', sa.Date(), nullable=True),
    sa.Column('passo_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('data_modificacao', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['passo_id'], ['passos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('custos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custos_data_ocorrencia'), ['data_ocorrencia'], unique=False)
        batch_op.create_index(batch_op.f('ix_custos_passo_id'), ['passo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custos_tipo_custo'), ['tipo_custo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custos_tipo_custo'))
        batch_op.drop_index(batch_op.f('ix_custos_passo_id'))
        batch_op.drop_index(batch_op.f('ix_custos_data_ocorrencia'))

    op.drop_table('custos')
    with op.batch_alter_table('passos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_passos_tipo'))
        batch_op.drop_index(batch_op.f('ix_passos_jornada_id'))

    op.drop_table('passos')
    with op.batch_alter_table('jornadas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jornadas_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_jornadas_nome'))

    op.drop_table('jornadas')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    # ### end Alembic commands ###
